=== just-recipes/just-recipes.github.io/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Recipe",
  "type": "object",
  "required": ["title", "prepTime", "cookTime", "yield", "ingredients", "instructions"],
  "properties": {
    "title": {
      "type": "string"
    },
    "prepTime": {
      "type": "string",
      "format": "duration"
    },
    "cookTime": {
      "type": "string",
      "format": "duration"
    },
    "ovenTemperature": {
      "type": "object",
      "properties": {
        "value": { "type": "number" },
        "unit": { "type": "string", "enum": ["F", "C"] }
      },
      "required": ["value", "unit"]
    },
    "yield": {
      "type": "string"
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name"],
        "properties": {
          "amount": { "type": "number" },
          "unit": { "type": "string", "enum": [
            "tsp",
            "tbsp",
            "cup",
            "fl oz",
            "oz",
            "lb",
            "g",
            "kg",
            "mL",
            "L",
            "pinch",
            "dash",
            "clove",
            "stick",
            "pkg",
            "can",
            "fillet"
          ] },
          "name": { "type": "string" },
          "preparation": { "type": "string" },
          "optional": { "type": "boolean" }
        }
      }
    },
    "instructions": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["stepNumber", "text"],
        "properties": {
          "stepNumber": { "type": "integer" },
          "text": { "type": "string" },
          "duration": { "type": "string", "format": "duration" }
        }
      }
    }
  }
}

=== just-recipes/just-recipes.github.io/data/honey-glazed-salmon.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Honey Glazed Salmon",
    "prepTime": "PT5M",
    "cookTime": "PT15M",
    "yield": "4 servings",
    "ovenTemperature": {
        "value": 425,
        "unit": "F"
    },
    "ingredients": [
        {
            "amount": 4,
            "unit": "fillet",
            "name": "salmon"
        },
        {
            "amount": 0.25,
            "unit": "cup",
            "name": "salted butter"
        },
        {
            "amount": 4,
            "unit": "clove",
            "name": "garlic"
        },
        {
            "amount": 0.33,
            "unit": "cup",
            "name": "honey"
        },
        {
            "amount": 4,
            "unit": "tbsp",
            "name": "soy sauce"
        },
        {
            "amount": 1,
            "unit": "tsp",
            "name": "sea salt"
        },
        {
            "amount": 0.5,
            "unit": "tsp",
            "name": "ground black pepper"
        },
        {
            "amount": 1,
            "unit": "tsp",
            "name": "garlic powder"
        }
    ],
    "instructions": [
        {
            "stepNumber": 1,
            "text": "Preheat the oven and line a baking sheet with aluminum foil."
        },
        {
            "stepNumber": 2,
            "text": "Heat a medium saucepan over medium heat. Add butter, garlic, honey, and soy sauce. Whisk until smooth. Cook for 3 minutes.",
            "duration": "PT3M"
        },
        {
            "stepNumber": 3,
            "text": "Place salmon fillets on the baking sheet. Season with sea salt, black pepper, and garlic powder. Pour the honey glaze over the salmon fillets. Bake for 12 minutes. Safe temperature is 145 degrees F.",
            "duration": "PT12M"
        }
    ]

}

=== just-recipes/just-recipes.github.io/data/chocolate-chip-cookies.json
{
  "$schema": "../schemas/recipe.schema.json",
  "title": "Chocolate Chip Cookies",
  "prepTime": "25 minutes",
  "cookTime": "8 minutes per batch",
  "ovenTemperature": {
    "value": 375,
    "unit": "F"
  },
  "yield": "about 60 cookies",
  "ingredients": [
    {
      "amount": 0.5,
      "unit": "cup",
      "name": "shortening"
    },
    {
      "amount": 0.5,
      "unit": "cup",
      "name": "butter",
      "preparation": "softened"
    },
    {
      "amount": 1,
      "unit": "cup",
      "name": "brown sugar",
      "preparation": "packed"
    },
    {
      "amount": 0.5,
      "unit": "cup",
      "name": "granulated sugar"
    },
    {
      "amount": 0.5,
      "unit": "tsp",
      "name": "baking soda"
    },
    {
      "amount": 2,
      "name": "eggs"
    },
    {
      "amount": 1,
      "unit": "tsp",
      "name": "vanilla"
    },
    {
      "amount": 2.5,
      "unit": "cup",
      "name": "all-purpose flour"
    },
    {
      "amount": 2,
      "unit": "cup",
      "name": "semi-sweet chocolate pieces"
    },
    {
      "amount": 1.5,
      "unit": "cup",
      "name": "chipped walnuts, pecans, or hazelnuts",
      "optional": true
    }
  ],
  "instructions": [
    {
      "stepNumber": 1,
      "text": "In a large mixing bowl beat shortening and butter with an electric mixer on medium to high speed for 30 seconds. Add brown sugar, granulated sugar, and baking soda. Beat until mixture is combined, scraping sides of bowl occasionally. Beat in eggs and vanilla until combined. Beat in as much of the flour as you can with the mixer. Stir in any remaining flour. Stir in chocolate pieces and, if desired, nuts.",
      "timerMinutes": 1
    },
    {
      "stepNumber": 2,
      "text": "Drop dough by rounded teaspoons 2 inches apart onto an ungreased cookie sheet. Bake in a 375 F oven or until edges are lightly browned. Transfer to a wire rack and let cool.",
      "timerMinutes": 9
    }
  ]
}

=== just-recipes/just-recipes.github.io/data/pulled-pork.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Pulled Pork",
    "prepTime": "PT10M",
    "cookTime": "PT50M",
    "yield": "6 servings",
    "ingredients": [
        {
            "amount": 1,
            "unit": "tbsp",
            "name": "Brown sugar"
        },
        {
            "amount": 2,
            "unit": "tsp",
            "name": "Paprika"
        },
        {
            "amount": 2,
            "unit": "tsp",
            "name": "Garlic powder"
        },
        {
            "amount": 2,
            "unit": "tsp",
            "name": "Onion powder"
        },
        {
            "amount": 1,
            "unit": "tsp",
            "name": "Salt"
        },
        {
            "amount": 1,
            "unit": "tsp",
            "name": "Pepper"
        },
        {
            "amount": 0.5,
            "unit": "tsp",
            "name": "Cumin"
        },
        {
            "amount": 0.25,
            "unit": "tsp",
            "name": "Cayenne pepper",
            "optional": true
        },
        {
            "amount": 3,
            "unit": "lb",
            "name": "Pork roast",
            "preparation": "Cut into 3 inch cubes"
        },
        {
            "amount": 2,
            "unit": "tbsp",
            "name": "Olive oil"
        },
        {
            "amount": 0.33,
            "unit": "cup",
            "name": "Beer",
            "preparation": "The rest is for you!"
        },
        {
            "amount": 2,
            "unit": "cup",
            "name": "Barbecue sauce",
            "preparation": "Divided"
        },
        {
            "amount": 1.25,
            "unit": "cup",
            "name": "Chicken or beef broth"
        }
    ],
    "instructions": [
        {
            "stepNumber": 1,
            "text": "In a small bowl mix together the brown sugar and spices."
        },
        {
            "stepNumber": 2,
            "text": "Season the cubed pork with the spice mixture and set aside."
        },
        {
            "stepNumber": 3,
            "text": "In a medium bowl whisk together the apple cider vinegar, half of the barbecue sauce, and one cup of the broth."
        },
        {
            "stepNumber": 4,
            "text": "Turn the instant pot onto the sauté setting.  Add olive oil and wait for it to heat."
        },
        {
            "stepNumber": 5,
            "text": "Add the seasoned pork to the instant pot and cook for 5 minutes."
        },
        {
            "stepNumber": 6,
            "text": "Add the barbecue sauce mixture to the instant pot.  Close the lid and cook on high pressure for 40 minutes.",
            "timer": "PT40M"
        },
        {
            "stepNumber": 7,
            "text": "Allow the pressure to release naturally for 10 minutes.",
            "timer": "PT10M"
        },
        {
            "stepNumber": 8,
            "text": "Remove meat and put in the stand mixer bowl.  Add the remaining barbecue sauce and shred."
        }
    ]
}
